// Draws brand/icon.svg — the app icon.
//
// The first attempt hand-waved the land as a few wavy bands and the result
// looked like a finance chart: meaningless shapes with a zigzag over them.
// The land here is the real coastline, the same Natural Earth data the app
// itself paints, in the same orthographic projection, centred where the book
// is: the eastern Mediterranean. Drawing it from the data rather than from
// memory is both more honest and, at 48px, more legible — real coastlines
// have a silhouette that invented blobs do not.
//
// House style, matched to yswords / seeksparks / news-insights: a pale
// tinted ground filling the square, one large object in a mid tone, a heavy
// darker outline, pale details inside. Different colour, as asked — this
// app's navy sea, parchment land and gilded coast.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SIZE = 1024, CX = 512, CY = 512, R = 352;
// Centred on the Levant: the land the text spends most of its time on.
const LON0 = 34 * Math.PI / 180, LAT0 = 30 * Math.PI / 180;

const land = JSON.parse(readFileSync(join(ROOT, 'public/data/ne_110m_land.geojson'), 'utf8'));

/** Orthographic: the globe as seen from far away, which is what the app draws. */
function project(lon, lat) {
  const l = lon * Math.PI / 180, p = lat * Math.PI / 180;
  const cosc = Math.sin(LAT0) * Math.sin(p) + Math.cos(LAT0) * Math.cos(p) * Math.cos(l - LON0);
  if (cosc <= 0) return null; // the far side of the world
  return [
    CX + R * Math.cos(p) * Math.sin(l - LON0),
    CY - R * (Math.cos(LAT0) * Math.sin(p) - Math.sin(LAT0) * Math.cos(p) * Math.cos(l - LON0)),
  ];
}

const round = (n) => Math.round(n * 10) / 10;

function ringPath(ring) {
  let d = '', pen = false;
  for (const [lon, lat] of ring) {
    const pt = project(lon, lat);
    if (!pt) { pen = false; continue; }   // went over the horizon
    d += `${pen ? 'L' : 'M'}${round(pt[0])} ${round(pt[1])}`;
    pen = true;
  }
  return d ? d + 'Z' : '';
}

const paths = [];
for (const f of land.features) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) {
    // Outer ring only: at this size a lake reads as a blemish, not a lake.
    const d = ringPath(poly[0]);
    if (d.length > 40) paths.push(d);
  }
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}">
  <!-- Generated by scripts/build-icon.mjs — edit that, not this.
       Coastline: Natural Earth 110m (public domain), orthographic, centred
       on the eastern Mediterranean. Same land the app paints. -->
  <defs>
    <clipPath id="globe"><circle cx="${CX}" cy="${CY}" r="${R}"/></clipPath>
  </defs>

  <rect width="${SIZE}" height="${SIZE}" fill="#ecdcbc"/>

  <circle cx="${CX}" cy="${CY}" r="${R}" fill="#16324f"/>

  <g clip-path="url(#globe)">
    <g fill="#f1e8d4">
${paths.map((d) => `      <path d="${d}"/>`).join('\n')}
    </g>
    <g fill="none" stroke="#ecdcbc" stroke-width="6" opacity=".18">
      <ellipse cx="${CX}" cy="${CY}" rx="${R * 0.5}" ry="${R}"/>
      <path d="M${CX - R} ${CY}h${R * 2}"/>
    </g>
  </g>

  <!-- the gilded coast, then the heavy outline the family's icons all carry -->
  <circle cx="${CX}" cy="${CY}" r="${R - 13}" fill="none" stroke="#c9a227" stroke-width="9" opacity=".9"/>
  <circle cx="${CX}" cy="${CY}" r="${R}" fill="none" stroke="#11263c" stroke-width="26"/>

  <!-- A place named, which is what an atlas is for. The tip lands on the
       centre of the projection, which is the Levant — so the pin marks the
       ground the book stands on rather than floating over the sea. -->
  <g transform="translate(${CX} ${CY}) scale(.88) translate(0 -96)">
    <path d="M0 96C0 96 74 26 74 -28A74 74 0 0 0 -74 -28C-74 26 0 96 0 96Z"
          fill="#e8c55a" stroke="#11263c" stroke-width="24" stroke-linejoin="round"/>
    <circle cx="0" cy="-28" r="26" fill="#16324f"/>
  </g>
</svg>
`;

mkdirSync(join(ROOT, 'brand'), { recursive: true });
writeFileSync(join(ROOT, 'brand/icon.svg'), svg);
console.log(`brand/icon.svg: ${paths.length} coastline rings`);
