#!/usr/bin/env bash
# Builds the signed release APK.
#
# src-tauri/gen/ is gitignored and regenerated by the Tauri CLI, so the
# signing configuration cannot simply live in the file it belongs in —
# `tauri android init` would wipe it and the next release would be signed
# with the debug key, which Android treats as a DIFFERENT APP: every
# installed copy would have to be uninstalled before it could update. So
# this script owns that configuration and re-applies it, idempotently,
# on every run.
#
# The keystore itself is never in the repository. It lives in ~/keys and is
# backed up in Google Drive under PasswordManager/, with a 说明.txt beside
# it recording the alias, the package name, the SHA-256 and what is lost if
# it goes missing (the answer: the ability to update every installed copy).
#
# Usage:
#   tools/build_apk.sh              # signed release APK
#   tools/build_apk.sh --install    # ...then install it on the attached device
set -euo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@17}"
export ANDROID_HOME="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
export NDK_HOME="${NDK_HOME:-$ANDROID_HOME/ndk/28.2.13676358}"
export PATH="$JAVA_HOME/bin:$HOME/.cargo/bin:$ANDROID_HOME/platform-tools:$PATH"

KEYSTORE="${KEYSTORE:-$HOME/keys/yahwehs-globe-release.jks}"
KEYSTORE_PW_FILE="${KEYSTORE_PW_FILE:-$HOME/keys/yahwehs-globe-release.pw}"
KEY_ALIAS="${KEY_ALIAS:-yahwehs-globe}"

INSTALL=0
for arg in "$@"; do
  case "$arg" in
    --install) INSTALL=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

for f in "$KEYSTORE" "$KEYSTORE_PW_FILE"; do
  if [ ! -s "$f" ]; then
    echo "REFUSING: $f is missing or empty." >&2
    echo "Without the release key this would build a debug-signed APK, which" >&2
    echo "Android cannot install over the released one. Restore it from" >&2
    echo "Google Drive: PasswordManager/yahwehs-globe/." >&2
    exit 1
  fi
done
if [ ! -x "$JAVA_HOME/bin/keytool" ]; then
  echo "REFUSING: no JDK at $JAVA_HOME (brew install openjdk@17)." >&2
  exit 1
fi

cd "$PROJECT"
ANDROID_DIR="src-tauri/gen/android"
if [ ! -d "$ANDROID_DIR" ]; then
  echo "==> gen/android missing; running tauri android init"
  cargo tauri android init
fi

# The password is read from the file and written into key.properties, which
# sits inside the gitignored gen/ tree. It is never echoed.
echo "==> writing $ANDROID_DIR/key.properties"
{
  printf 'storeFile=%s\n' "$KEYSTORE"
  printf 'keyAlias=%s\n' "$KEY_ALIAS"
  printf 'password=%s\n' "$(cat "$KEYSTORE_PW_FILE")"
} > "$ANDROID_DIR/key.properties"
chmod 600 "$ANDROID_DIR/key.properties"

# Patch the signing configuration into app/build.gradle.kts if this run (or a
# `tauri android init`) has produced a copy without it.
GRADLE="$ANDROID_DIR/app/build.gradle.kts"
if grep -q 'keyPropertiesFile' "$GRADLE"; then
  echo "==> signing config already present in app/build.gradle.kts"
else
  echo "==> adding the release signing config to app/build.gradle.kts"
  python3 - "$GRADLE" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1])
s = p.read_text()

loader = '''
val keyPropertiesFile = rootProject.file("key.properties")
val keyProperties = Properties().apply {
    if (keyPropertiesFile.exists()) {
        keyPropertiesFile.inputStream().use { load(it) }
    }
}
'''
anchor = "android {"
assert anchor in s, "could not find the android block"
s = s.replace(anchor, loader.strip() + "\n\n" + anchor, 1)

signing = '''    signingConfigs {
        create("release") {
            keyProperties.getProperty("storeFile")?.let {
                storeFile = file(it)
                storePassword = keyProperties.getProperty("password")
                keyAlias = keyProperties.getProperty("keyAlias")
                keyPassword = keyProperties.getProperty("password")
            }
        }
    }
'''
s = s.replace("    buildTypes {", signing + "    buildTypes {", 1)

rel = '''        getByName("release") {
            isMinifyEnabled = true'''
assert rel in s, "could not find the release build type"
s = s.replace(rel, '''        getByName("release") {
            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = true''', 1)

p.write_text(s)
print("   patched")
PY
fi

# The launcher name. Tauri writes strings.xml from productName at init time
# and there is no localised variant in what it generates, so a reader on a
# Chinese system would get the English name. Both are written here, and
# re-written on every run because `tauri android init` regenerates the file.
echo "==> setting the launcher name"
python3 - "$ANDROID_DIR" <<'PY'
import pathlib, re, sys
res = pathlib.Path(sys.argv[1]) / "app/src/main/res"
# The value is wrapped in double quotes, which is how an Android string
# resource carries a literal apostrophe — Tauri writes its own the same way.
# &apos; is valid XML and AAPT still refuses it: "Invalid unicode escape
# sequence in string", and the whole resource merge fails.
# Android picks the folder by the DEVICE's language, which is the whole
# point: a reader whose phone is in Chinese should see 雅伟之界 on the home
# screen without asking. What it does NOT do is fall back from zh-TW/zh-HK to
# values-zh — measured on the 0.1.5 APK, which reported
# application-label-zh-TW:'Yahweh's World' while zh-CN got 雅伟之界. So 繁體
# gets its own two folders, in 繁體, the way the app itself reads.
for values, label in [
    ("values", '"Yahweh\'s World"'),
    ("values-zh", '"雅伟之界"'),
    ("values-zh-rTW", '"雅偉之界"'),
    ("values-zh-rHK", '"雅偉之界"'),
]:
    d = res / values
    d.mkdir(parents=True, exist_ok=True)
    f = d / "strings.xml"
    if f.exists():
        text = f.read_text()
        new = text
        for key in ("app_name", "main_activity_title"):
            if f'name="{key}"' in new:
                new = re.sub(rf'(<string name="{key}">).*?(</string>)', lambda m: m.group(1) + label + m.group(2), new)
            else:
                new = new.replace('</resources>', f'    <string name="{key}">{label}</string>\n</resources>')
        f.write_text(new)
    else:
        f.write_text('<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
                     f'    <string name="app_name">{label}</string>\n'
                     f'    <string name="main_activity_title">{label}</string>\n</resources>\n')
    print(f"   {values}/strings.xml -> {label}")
PY

# The FIRST loading screen a reader on a phone sees, and it is not the one in
# the web app: between tapping the icon and the WebView painting anything,
# Android shows the launch theme. Tauri generates Theme.app with nothing in it,
# so that theme is Material's default — a flash of WHITE in front of an app
# whose every page is #060d16. On Android 12 and up this colour is also what
# the system splash draws the app icon on, so setting it buys a real splash
# screen; below 12 it is simply the window background instead of white.
# Rewritten on every run, because gen/ is regenerated.
echo "==> setting the launch screen"
python3 - "$ANDROID_DIR" <<'LAUNCH'
import pathlib, re, sys
res = pathlib.Path(sys.argv[1]) / "app/src/main/res"

# --ground from src/tokens.css. If that token ever moves this has to move with
# it: there is no way to read a CSS custom property from Gradle.
GROUND = "#060d16"
(res / "values").mkdir(parents=True, exist_ok=True)
(res / "values/colors.xml").write_text(
    '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
    '    <color name="ground">' + GROUND + '</color>\n</resources>\n')

ITEMS = (
    '        <item name="android:windowBackground">@color/ground</item>\n'
    '        <item name="android:statusBarColor">@color/ground</item>\n'
    '        <item name="android:navigationBarColor">@color/ground</item>\n'
    '        <item name="android:windowLightStatusBar">false</item>\n'
)
STYLE = re.compile(r'(<style name="Theme\.app"[^>]*>\n)')
for values in ("values", "values-night"):
    f = res / values / "themes.xml"
    if not f.exists():
        continue
    text = f.read_text()
    if "android:windowBackground" in text:
        print("   " + values + "/themes.xml already carries it")
        continue
    new, n = STYLE.subn(lambda m: m.group(1) + ITEMS, text, count=1)
    if n == 0:
        print("   !! could not find Theme.app in " + values, file=sys.stderr)
        continue
    f.write_text(new)
    print("   " + values + "/themes.xml -> windowBackground " + GROUND)

LAUNCH

# Android's mipmaps live in the gitignored gen/ tree, so a fresh
# `android init` would put Tauri's default icon back. Regenerated here
# from the one master in brand/.
echo "==> regenerating the app icons"
cargo tauri icon "$PROJECT/brand/icon-1024.png" >/dev/null

echo "==> building the release APK"
cargo tauri android build --apk

APK="$(find "$ANDROID_DIR/app/build/outputs/apk/universal/release" -name '*.apk' 2>/dev/null | head -1)"
if [ -z "$APK" ]; then
  APK="$(find "$ANDROID_DIR/app/build/outputs/apk" -name '*release*.apk' 2>/dev/null | head -1)"
fi
if [ -z "$APK" ]; then
  echo "!!! the build reported success but no release APK was produced." >&2
  exit 1
fi

# An APK is only released if it carries the release key. apksigner reports
# the certificate that actually signed it, which is the only answer that
# cannot be wrong — a debug-signed APK also builds, installs and runs.
APKSIGNER="$(find "$ANDROID_HOME/build-tools" -name apksigner | sort -r | head -1)"
echo "==> verifying the signature"
"$APKSIGNER" verify --print-certs "$APK" | grep -E "Signer #1 certificate (DN|SHA-256)"

# What the APK SAYS it is, read back off the file itself.
#
# This exists because a 0.1.4 APK was once uploaded to the 0.1.5 release: the
# file was copied out of this directory while Gradle was still writing the new
# one, and every check up to that point had looked at the build's intent rather
# than at the artifact. A wrong version here is not cosmetic — the in-app
# update check compares this string to the latest release tag, so a stale APK
# would tell every reader forever that an update is available.
AAPT2="$(find "$ANDROID_HOME/build-tools" -name aapt2 | sort -r | head -1)"
WANT="$(awk -F'"' '/^[[:space:]]*"version":/ {print $4; exit}' "$PROJECT/src-tauri/tauri.conf.json")"
GOT="$("$AAPT2" dump badging "$APK" | sed -n "s/.*versionName='\([^']*\)'.*/\1/p" | head -1)"
echo "==> verifying the version"
if [ "$WANT" != "$GOT" ]; then
  echo "REFUSING: the APK says versionName=$GOT, tauri.conf.json says $WANT." >&2
  echo "Do not ship this file. It is almost certainly a previous build that" >&2
  echo "was picked up before Gradle finished writing the new one." >&2
  exit 1
fi
echo "   versionName=$GOT (matches tauri.conf.json)"

# What the file is CALLED matters: it is what a reader downloads and what
# sits in their Downloads folder afterwards. Gradle names it after its own
# module, which is how "app-universal-release.apk" ends up on a release page.
RELEASE_DIR="$PROJECT/dist-app"
mkdir -p "$RELEASE_DIR"
NAMED="$RELEASE_DIR/YahwehsWorld-$GOT.apk"
cp "$APK" "$NAMED"

echo
echo "✓ $NAMED"
ls -lh "$NAMED" | awk '{print "  " $5}'
echo "  (built from $APK)"

if [ "$INSTALL" = "1" ]; then
  # With an emulator also running, a bare `adb install` fails with "more than
  # one device". Prefer a real device — an emulator is not what anyone means
  # by "install it on my tablet" — unless ANDROID_SERIAL names one.
  TARGET="${ANDROID_SERIAL:-$(adb devices | awk '$2=="device" && $1 !~ /^emulator-/ {print $1; exit}')}"
  if [ -z "$TARGET" ]; then
    echo "!!! no device attached to install on (emulators are skipped)." >&2
    echo "!!! the APK above is built and signed; attach a device and run:" >&2
    echo "!!!   adb install -r $APK" >&2
    exit 1
  fi
  echo "==> installing on $TARGET"
  # MIUI refuses adb installs unless "USB 安装" is on in developer options,
  # and reports it as INSTALL_FAILED_USER_RESTRICTED / "canceled by user".
  adb -s "$TARGET" install -r "$APK"
fi
