#!/usr/bin/env bash
# Builds the signed release APK.
#
# src-tauri/gen/ is gitignored and regenerated by the Tauri CLI, so the
# signing configuration cannot simply live in the file it belongs in —
# `tauri android init` would wipe it and the next release would be signed
# with the debug key, which Android treats as a DIFFERENT APP: every
# installed copy would have to be uninstalled before it could update. So
# this script owns that configuration and re-applies it, idempotently,
# on every run.
#
# The keystore itself is never in the repository. It lives in ~/keys and is
# backed up in Google Drive under PasswordManager/, with a 说明.txt beside
# it recording the alias, the package name, the SHA-256 and what is lost if
# it goes missing (the answer: the ability to update every installed copy).
#
# Usage:
#   tools/build_apk.sh              # signed release APK
#   tools/build_apk.sh --install    # ...then install it on the attached device
set -euo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@17}"
export ANDROID_HOME="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
export NDK_HOME="${NDK_HOME:-$ANDROID_HOME/ndk/28.2.13676358}"
export PATH="$JAVA_HOME/bin:$HOME/.cargo/bin:$ANDROID_HOME/platform-tools:$PATH"

KEYSTORE="${KEYSTORE:-$HOME/keys/yahwehs-globe-release.jks}"
KEYSTORE_PW_FILE="${KEYSTORE_PW_FILE:-$HOME/keys/yahwehs-globe-release.pw}"
KEY_ALIAS="${KEY_ALIAS:-yahwehs-globe}"

INSTALL=0
for arg in "$@"; do
  case "$arg" in
    --install) INSTALL=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

for f in "$KEYSTORE" "$KEYSTORE_PW_FILE"; do
  if [ ! -s "$f" ]; then
    echo "REFUSING: $f is missing or empty." >&2
    echo "Without the release key this would build a debug-signed APK, which" >&2
    echo "Android cannot install over the released one. Restore it from" >&2
    echo "Google Drive: PasswordManager/yahwehs-globe/." >&2
    exit 1
  fi
done
if [ ! -x "$JAVA_HOME/bin/keytool" ]; then
  echo "REFUSING: no JDK at $JAVA_HOME (brew install openjdk@17)." >&2
  exit 1
fi

cd "$PROJECT"
ANDROID_DIR="src-tauri/gen/android"
if [ ! -d "$ANDROID_DIR" ]; then
  echo "==> gen/android missing; running tauri android init"
  cargo tauri android init
fi

# The password is read from the file and written into key.properties, which
# sits inside the gitignored gen/ tree. It is never echoed.
echo "==> writing $ANDROID_DIR/key.properties"
{
  printf 'storeFile=%s\n' "$KEYSTORE"
  printf 'keyAlias=%s\n' "$KEY_ALIAS"
  printf 'password=%s\n' "$(cat "$KEYSTORE_PW_FILE")"
} > "$ANDROID_DIR/key.properties"
chmod 600 "$ANDROID_DIR/key.properties"

# Patch the signing configuration into app/build.gradle.kts if this run (or a
# `tauri android init`) has produced a copy without it.
GRADLE="$ANDROID_DIR/app/build.gradle.kts"
if grep -q 'keyPropertiesFile' "$GRADLE"; then
  echo "==> signing config already present in app/build.gradle.kts"
else
  echo "==> adding the release signing config to app/build.gradle.kts"
  python3 - "$GRADLE" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1])
s = p.read_text()

loader = '''
val keyPropertiesFile = rootProject.file("key.properties")
val keyProperties = Properties().apply {
    if (keyPropertiesFile.exists()) {
        keyPropertiesFile.inputStream().use { load(it) }
    }
}
'''
anchor = "android {"
assert anchor in s, "could not find the android block"
s = s.replace(anchor, loader.strip() + "\n\n" + anchor, 1)

signing = '''    signingConfigs {
        create("release") {
            keyProperties.getProperty("storeFile")?.let {
                storeFile = file(it)
                storePassword = keyProperties.getProperty("password")
                keyAlias = keyProperties.getProperty("keyAlias")
                keyPassword = keyProperties.getProperty("password")
            }
        }
    }
'''
s = s.replace("    buildTypes {", signing + "    buildTypes {", 1)

rel = '''        getByName("release") {
            isMinifyEnabled = true'''
assert rel in s, "could not find the release build type"
s = s.replace(rel, '''        getByName("release") {
            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = true''', 1)

p.write_text(s)
print("   patched")
PY
fi

echo "==> building the release APK"
cargo tauri android build --apk

APK="$(find "$ANDROID_DIR/app/build/outputs/apk/universal/release" -name '*.apk' 2>/dev/null | head -1)"
if [ -z "$APK" ]; then
  APK="$(find "$ANDROID_DIR/app/build/outputs/apk" -name '*release*.apk' 2>/dev/null | head -1)"
fi
if [ -z "$APK" ]; then
  echo "!!! the build reported success but no release APK was produced." >&2
  exit 1
fi

# An APK is only released if it carries the release key. apksigner reports
# the certificate that actually signed it, which is the only answer that
# cannot be wrong — a debug-signed APK also builds, installs and runs.
APKSIGNER="$(find "$ANDROID_HOME/build-tools" -name apksigner | sort -r | head -1)"
echo "==> verifying the signature"
"$APKSIGNER" verify --print-certs "$APK" | grep -E "Signer #1 certificate (DN|SHA-256)"

echo
echo "✓ $APK"
ls -lh "$APK" | awk '{print "  " $5}'

if [ "$INSTALL" = "1" ]; then
  echo "==> installing on the attached device"
  adb install -r "$APK"
fi
