#!/usr/bin/env bash
# Bumps yahwehs-globe's release version in lock-step across every
# machine-read manifest: package.json and src-tauri/tauri.conf.json.
# Ported from SeekSparks' tools/bump_version.sh (same reasoning: the
# version number is a deliberate release marker, not a progress
# counter, so it moves only when this is called).
#
# There is no per-project constants file to keep in sync here — Tauri's
# getVersion() reads tauri.conf.json directly at runtime on native
# builds, and Android's versionCode/versionName regenerate from it
# automatically the next time `tauri android build` runs (see
# src-tauri/gen/android/app/tauri.properties, which is gitignored and
# autogenerated). Two files, not four.
#
# Usage:
#   tools/bump_version.sh           # bump patch by 1 (0.1.0 -> 0.1.1)
#   tools/bump_version.sh --print   # just print current version
#   tools/bump_version.sh --set 0.2.0  # set explicit version
set -euo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKAGE_JSON="$PROJECT/package.json"
TAURI_CONF="$PROJECT/src-tauri/tauri.conf.json"
CARGO_TOML="$PROJECT/src-tauri/Cargo.toml"

current_version() {
  awk -F'"' '/^[[:space:]]*"version":/ {print $4; exit}' "$PACKAGE_JSON"
}

case "${1:-}" in
  --print)
    current_version
    exit 0
    ;;
  --set)
    if [[ -z "${2:-}" ]]; then
      echo "bump_version.sh: --set requires a version argument" >&2
      exit 2
    fi
    NEW="$2"
    ;;
  *)
    CUR="$(current_version)"
    IFS='.' read -r MA MI PA <<<"$CUR"
    NEW="$MA.$MI.$((PA + 1))"
    ;;
esac

echo "==> bumping version: $(current_version) -> $NEW"

for f in "$PACKAGE_JSON" "$TAURI_CONF"; do
  TMP="$(mktemp)"
  awk -v new="$NEW" '
    !done && /^[[:space:]]*"version":/ {
      sub(/"version":[[:space:]]*"[^"]*"/, "\"version\": \"" new "\"")
      done = 1
    }
    { print }
  ' "$f" >"$TMP"
  mv "$TMP" "$f"
done

# The crate version is not what the app reports — getVersion() reads
# tauri.conf.json — but a crate that says 0.1.0 while the app ships 0.1.4 is
# the drift this script exists to prevent, and it is one line to keep true.
TMP="$(mktemp)"
awk -v new="$NEW" '
  !done && /^version[[:space:]]*=/ { print "version = \"" new "\""; done = 1; next }
  { print }
' "$CARGO_TOML" >"$TMP"
mv "$TMP" "$CARGO_TOML"

echo "✓ package.json + tauri.conf.json + Cargo.toml now at $NEW"
